/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BlogIndexImport } from './routes/blog/index'
import { Route as BlogIdImport } from './routes/blog/$id'
import { Route as BlogTagsIdImport } from './routes/blog/tags/$id'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IdentityRfcNotesIndexLazyImport = createFileRoute(
  '/identity/rfc-notes/',
)()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  path: '/blog/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIdRoute = BlogIdImport.update({
  path: '/blog/$id',
  getParentRoute: () => rootRoute,
} as any)

const IdentityRfcNotesIndexLazyRoute = IdentityRfcNotesIndexLazyImport.update({
  path: '/identity/rfc-notes/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/identity/rfc-notes/index.lazy').then((d) => d.Route),
)

const BlogTagsIdRoute = BlogTagsIdImport.update({
  path: '/blog/tags/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdImport
      parentRoute: typeof rootRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof rootRoute
    }
    '/blog/tags/$id': {
      id: '/blog/tags/$id'
      path: '/blog/tags/$id'
      fullPath: '/blog/tags/$id'
      preLoaderRoute: typeof BlogTagsIdImport
      parentRoute: typeof rootRoute
    }
    '/identity/rfc-notes/': {
      id: '/identity/rfc-notes/'
      path: '/identity/rfc-notes'
      fullPath: '/identity/rfc-notes'
      preLoaderRoute: typeof IdentityRfcNotesIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog': typeof BlogIndexRoute
  '/blog/tags/$id': typeof BlogTagsIdRoute
  '/identity/rfc-notes': typeof IdentityRfcNotesIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog': typeof BlogIndexRoute
  '/blog/tags/$id': typeof BlogTagsIdRoute
  '/identity/rfc-notes': typeof IdentityRfcNotesIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/tags/$id': typeof BlogTagsIdRoute
  '/identity/rfc-notes/': typeof IdentityRfcNotesIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog/$id'
    | '/blog'
    | '/blog/tags/$id'
    | '/identity/rfc-notes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog/$id'
    | '/blog'
    | '/blog/tags/$id'
    | '/identity/rfc-notes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog/$id'
    | '/blog/'
    | '/blog/tags/$id'
    | '/identity/rfc-notes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutLazyRoute: typeof AboutLazyRoute
  BlogIdRoute: typeof BlogIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogTagsIdRoute: typeof BlogTagsIdRoute
  IdentityRfcNotesIndexLazyRoute: typeof IdentityRfcNotesIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutLazyRoute: AboutLazyRoute,
  BlogIdRoute: BlogIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogTagsIdRoute: BlogTagsIdRoute,
  IdentityRfcNotesIndexLazyRoute: IdentityRfcNotesIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/blog/$id",
        "/blog/",
        "/blog/tags/$id",
        "/identity/rfc-notes/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/blog/$id": {
      "filePath": "blog/$id.tsx"
    },
    "/blog/": {
      "filePath": "blog/index.tsx"
    },
    "/blog/tags/$id": {
      "filePath": "blog/tags/$id.tsx"
    },
    "/identity/rfc-notes/": {
      "filePath": "identity/rfc-notes/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
